#!/usr/bin/env python3
"""Serialise the two compiler tables into plain-text data files (M-TOOL).

The GOLF-written build tools under `gtools/` have to know exactly what
`tools/codepage.py` and `tools/mkblob2.py` know: the byte<->glyph<->mnemonic
code page, and the machine-code template blob.  Today both live as **Python
literals**, and a GOLF program cannot read a Python literal.

Nor can it carry a copy of the code page as GOLF source.  A `“...“` string
literal cannot contain byte 0x8E (that byte *is* the delimiter), and
`tools/codepage.py`'s encoder is not string-aware anyway: inside a literal a `#`
would still eat the rest of the line, a `\\` would still start a mnemonic
escape, and every non-ASCII character must already be a code-page glyph.  A
table of glyphs is precisely the thing that cannot be written down that way.

So the tables become **data**: generated here by Python, checked in, and read at
runtime by the GOLF tools.  Python stays the single source of truth — nothing
below invents a byte, a glyph or a template; every value is read back out of
`mkblob2`/`codepage`, which are the registry-disciplined tables
(`../REGISTRY.md`).  This script only reformats.  That is why the blob is
serialised by *parsing what `build_blob2()` actually emitted* rather than by
walking `ATOMS` a second time: a second walk would be a second implementation of
the emission policy (record order, and the M-VEC overrides that REPLACE a scalar
record instead of following it), and a second implementation is a second thing
that can drift.

Both outputs are GENERATED — never hand-edit them; run `python3
tools/mktables.py` from `expanded/` and commit the result.  `test/selfcheck.sh`
re-derives them and fails if what is committed differs, which is what keeps them
honest when someone adds an atom to `mkblob2.ATOMS`.

Design constraints on the formats, all three of them for the reader's sake:

  * **ASCII only, one record per line, one separator.**  The consumer is a
    stack language with no string library; it can afford "scan to the next
    delimiter" and nothing more.
  * **Everything in hex, including the glyphs.**  GOLF is a byte machine, and a
    raw-UTF-8 glyph column would additionally make the *file's own* encoding
    load-bearing — a stray editor re-encode would silently change the code page.
    Hex is inert.
  * **A leading-`#` header.**  GOLF's own comment rule is "`#` to end of line",
    so a reader that already skips comments skips the header for free, and the
    format gets to document itself in the file it describes.

Usage:
  python3 tools/mktables.py        # (re)write data/codepage.tsv, data/blob.hex
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import mkblob2                     # ATOMS + build_blob2(): the two sources
import codepage                    # COMPILER + LIB, and the dicts we must match

DATA = os.path.join(HERE, "..", "data")

# A byte decodes back to its glyph exactly when it is >= 0x80 — `codepage.decode`
# renders anything below that as plain ASCII.  That is what makes a LIB row keyed
# by a letter encode-only (⍳ and \range both encode to byte 'R', but decode shows
# `R`, since a low byte could equally be a *user* word of that name), and it is
# the same cut for the five ASCII-byte ATOMS (`~ $ | = >`, whose glyph IS their
# ASCII character, so nothing is lost).
HIGH_BYTE = 0x80


def codepage_rows():
    """The code page as (byte, mode, src, mnemonic, glyph) tuples.

    In `codepage.all_rows()` order — ATOMS, then COMPILER, then LIB — which is
    also the order the module's own dicts are built in.  Order is not actually
    load-bearing here (`codepage.py check` guarantees bytes, mnemonics and
    glyphs are each unique across all three tables, so no reader can see a
    conflict to resolve), but matching the Python keeps diffs readable.
    """
    rows  = [(b, "A", mn, gl) for b, mn, gl, _t, _d in mkblob2.ATOMS]
    rows += [(b, "C", mn, gl) for b, mn, gl, _d in codepage.COMPILER]
    rows += [(codepage.lib_byte(k), "L", mn, gl)
             for k, mn, gl, _d in codepage.LIB]
    return [(b, "ED" if b >= HIGH_BYTE else "E-", src, mn, gl)
            for b, src, mn, gl in rows]


CODEPAGE_HEADER = """\
# expanded/data/codepage.tsv -- the GOLF code page, as data.
#
# GENERATED by tools/mktables.py from tools/mkblob2.py's ATOMS and
# tools/codepage.py's COMPILER and LIB tables.  Do not hand-edit: run
# `python3 tools/mktables.py` from expanded/ and commit.  test/selfcheck.sh
# fails if this file is not exactly what that command emits.
#
# It carries everything needed to reproduce BOTH codepage.encode and
# codepage.decode.  One record per line, five TAB-separated ASCII fields:
#
#   byte  mode  src  mnemonic  glyph
#
#   byte      the op byte, two uppercase hex digits
#   mode      ED = this byte decodes back to this glyph/mnemonic
#             E- = encode-only (see below)
#   src       A = mkblob2.ATOMS, C = codepage.COMPILER, L = codepage.LIB
#   mnemonic  the \\name spelling WITHOUT the backslash, ASCII letters only
#   glyph     the glyph's UTF-8 bytes, two uppercase hex digits each, no spaces
#
# The three fixed-width fields come first, so the head of every record is
# exactly seven characters and a reader that only wants the byte can stop after
# two of them; the variable-width fields follow.  Glyphs are hex-encoded rather
# than written literally because the consumer is a byte machine and because a
# literal column would make this file's own encoding load-bearing.
#
# ENCODING uses every row: mnemonic -> byte and glyph -> byte, both regardless
# of mode.  (The encoder takes the LONGEST KNOWN MNEMONIC PREFIX of the alpha
# run after a `\\`, so \\sqr48 is \\sqr then 48 -- see ../REGISTRY.md.)
#
# DECODING uses only the ED rows: byte -> glyph, or byte -> \\mnemonic in -m
# form.  The E- rows are the deliberate asymmetry documented in
# tools/codepage.py: a LIB word named by an ASCII letter is reachable by its
# glyph and its mnemonic on input, but that byte decodes as the plain letter,
# because a low byte could equally be a *user* word of the same name.  Bytes
# with no row at all decode as ASCII, or as \\xHH when they are neither.
#
# Lines beginning with `#` are comments and there are none after this header;
# there is no blank line and no trailing whitespace anywhere in the records.
"""


def build_codepage_tsv():
    """data/codepage.tsv — the byte/glyph/mnemonic table, in the format above."""
    out = [CODEPAGE_HEADER]
    for b, mode, src, mn, gl in codepage_rows():
        glyph_hex = gl.encode("utf-8").hex().upper()
        out.append(f"{b:02X}\t{mode}\t{src}\t{mn}\t{glyph_hex}\n")
    return "".join(out).encode("ascii")


def blob_records():
    """`mkblob2.build_blob2()` split back into its [key][len][data] records.

    Parsing the real output rather than re-deriving it is the whole point: the
    emission ORDER is load-bearing (the compiler's record lookup returns the
    FIRST match for a key) and so are the M-VEC overrides, which replace a
    record rather than following it.  Reading the bytes back keeps both policies
    where they belong — in build_blob2 — and leaves this file, and the GOLF tool
    that consumes it, as dumb formatters that cannot get them wrong.
    """
    blob, recs, i = mkblob2.build_blob2(), [], 0
    while blob[i]:                       # key 0 is the terminating sentinel
        key, n = blob[i], blob[i + 1]
        recs.append((key, blob[i + 2:i + 2 + n]))
        i += 2 + n
    assert i + 1 == len(blob), f"trailing bytes after the sentinel at {i}"
    return recs


BLOB_HEADER = """\
# expanded/data/blob.hex -- the machine-code template blob, as data.
#
# GENERATED by tools/mktables.py from tools/mkblob2.py's build_blob2().  Do not
# hand-edit: run `python3 tools/mktables.py` from expanded/ and commit.
# test/selfcheck.sh fails if this file is not exactly what that command emits.
#
# The blob is the template table both generated compilers embed (see
# tools/mkblob2.py): a sequence of [key][len][len bytes] records terminated by a
# 0 key byte.  Keys 1-5 are the fixed sections -- 1 prologue, 2 cond, 3 startup,
# 4 the ELF header's non-zero (offset,value) pairs, 5 autoexit -- and every
# record after them is one op byte's machine-code template, keyed by that byte.
#
# One record per line, in EXACTLY build_blob2()'s emission order, with the M-VEC
# OVERRIDES already substituted for the scalar records they replace.  Both of
# those are policy, and both are already decided by the time this file is
# written: order matters because the compiler's record lookup returns the FIRST
# match for a key, and an override REPLACES its record rather than following it
# (emitting both would be a silent no-op).  A reader here is a formatter, not a
# policy engine -- concatenate the lines and you have the blob.
#
# Each line is one whole record: its bytes as two uppercase hex digits each,
# separated by single spaces.  So the first field is the key, the second is the
# length, and the rest is the template -- the same [key][len][data] the blob has,
# just spelled out.
#
# The terminating 0 sentinel is NOT in this file, and the reader appends it.  A
# bare `00` line would be the one line that is not a key+len+data record, so
# every consumer would need a special case for the last line; appending one byte
# is cheaper, and leaving it out means a truncated file cannot look complete.
#
# Lines beginning with `#` are comments; the last of them is the one-line
# summary below, and every line after that is a record.
"""


def build_blob_hex():
    """data/blob.hex — one line per blob record, in the format above."""
    recs = blob_records()
    total = sum(2 + len(d) for _k, d in recs) + 1        # + the sentinel
    out = [BLOB_HEADER,
           f"# {len(recs)} records, {total} bytes with the sentinel, "
           f"longest template {max(len(d) for _k, d in recs)}.\n"]
    for key, data in recs:
        rec = bytes([key, len(data)]) + data
        out.append(" ".join(f"{x:02X}" for x in rec) + "\n")
    return "".join(out).encode("ascii")


def _selfcheck():
    """Assert the serialised tables really do reproduce codepage.py.

    Cheap, and it fails here — at generation time, with the Python still in
    scope — rather than in a GOLF tool built on a table that quietly lost a row.
    """
    rows = codepage_rows()
    mnem = {mn: b for b, _mode, _src, mn, _gl in rows}
    glyph = {gl: b for b, _mode, _src, _mn, gl in rows}
    assert mnem == codepage.MNEM2BYTE, "mnemonic -> byte not reproducible"
    assert glyph == codepage.GLYPH2BYTE, "glyph -> byte not reproducible"

    # The ED rows alone must reproduce decode, in both of its output forms.
    b2g = {b: gl for b, mode, _src, _mn, gl in rows if mode == "ED"}
    b2m = {b: mn for b, mode, _src, mn, _gl in rows if mode == "ED"}
    def dec(data, mnemonic):
        out = []
        for b in data:
            if b in b2g:
                out.append(f"\\{b2m[b]}" if mnemonic else b2g[b])
            elif b in (9, 10) or 32 <= b < 127:
                out.append(chr(b))
            else:
                out.append(f"\\x{b:02X}")
        return "".join(out)
    every = bytes(range(256))
    for m in (False, True):
        assert dec(every, m) == codepage.decode(every, mnemonic=m), "decode differs"

    # And the hex lines must reassemble into the blob byte for byte.
    body = b"".join(bytes([k, len(d)]) + d for k, d in blob_records()) + b"\x00"
    assert body == mkblob2.build_blob2(), "blob records do not reassemble"


# name -> generator.  main() writes every one; test/selfcheck.sh re-derives them
# and compares against what is committed.
OUTPUTS = [("codepage.tsv", build_codepage_tsv), ("blob.hex", build_blob_hex)]


def main():
    _selfcheck()
    os.makedirs(DATA, exist_ok=True)
    for name, build in OUTPUTS:
        data = build()
        out = os.path.join(DATA, name)
        with open(out, "wb") as f:
            f.write(data)
        recs = sum(1 for ln in data.splitlines() if not ln.startswith(b"#"))
        sys.stderr.write(f"wrote {out}: {len(data)} bytes, {recs} records\n")


if __name__ == "__main__":
    main()
